name: noise_map_collector
description: "Aplikasi untuk mengumpulkan titik kebisingan (db meter) dan koordinat"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  noise_meter: ^5.1.0
  geolocator: ^14.0.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  flutter_sharing_intent: ^2.0.4
  package_info_plus: ^10.1.0
  share_plus: ^13.1.0

dependency_overrides:
  package_info_plus: ^10.1.0
  share_plus: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/noise_map_icon_1779817325491.png"
